[general]
import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Buttonless"
# opacity = 0.92
# blur = true

[font]
size = 9.0

[font.normal]
family =  "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family =  "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family =  "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family =  "JetBrainsMono Nerd Font"
style = "Bold Italic"

# family =  "MesloLGS Nerd Font Mono"
# normal.family = "JetBrainsMono Nerd Font"
# bold.family = "JetBrainsMono Nerd Font"
# normal.family = "FiraCode Nerd Font"

